# Generated by Django 5.1.2 on 2025-04-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
